<script lang="ts" context="module">
    import { fragment, query } from "svelte-pathfinder";
    import { schemas, records, type Item } from "$client/stores/data";
    import { files } from "$client/stores/files";
    import { date } from "$client/utils/time";

    import Await from "$client/components/Await.svelte";
    import Aside from "$client/components/Aside.svelte";
    import Icon from "$client/components/Icon.svelte";
    import Code from "$client/components/Code.svelte";
    import Input from "./record/input.svelte";
    import Checkbox from "./record/checkbox.svelte";
    import Textarea from "./record/textarea.svelte";
    import Select from "./record/select.svelte";
    import InputFile from "./record/file.svelte";
    import Json from "./record/json.svelte";
    import Markdown from "./record/markdown.svelte";

    import type { Schema } from "$client/stores/schemas";
</script>

<script lang="ts">
    export let collection: string = "";
    export let active: Item | undefined = undefined;
    export let open = false;
    export let close = () => query.set("");
    export let header = "Add record";

    const tabs = ["Form", "Code"];

    let activeTab = "Form";
    let recordID: number;

    function getRecord() {
        active = records.id(Number($query.record));
        recordID = active?.id || Date.now();
    }
    function makeRecord() {
        getRecord();
        return $schemas.map((s: any) => ({
            ...s,
            value: active?.[s.name],
            collection,
            recordID,
        }));
    }

    async function resetRecord(e: Event) {
        if (!active) {
            const data = new FormData(e.currentTarget as HTMLFormElement);
            const entries = Object.fromEntries(data);

            let fileNames: string[] = [];

            for (const name in entries) {
                const type = schemas.type(name);
                if (type === "file") {
                    const files: File[] = JSON.parse(String(entries[name]));
                    fileNames.push(...files.map(({ name }) => name));
                }
            }
            await files.delete(collection, fileNames);
        }
    }
    function submitRecord(e: SubmitEvent) {
        const data = new FormData(e.currentTarget as HTMLFormElement);
        const entries = Object.fromEntries(data);
        console.log(data, entries);

        const record: Record<string, any> = {};

        for (const name in entries) {
            const value = name === "id" ? Number(entries[name]) : entries[name];
            const type = schemas.type(name);

            switch (type) {
                case "checkbox":
                    record[name] = Boolean(value);
                    break;
                case "number":
                    record[name] = Number(value);
                    break;
                case "file":
                    record[name] = JSON.parse(String(value));
                    break;

                default:
                    record[name] = value;
                    break;
            }
        }

        $query.record === active?.id
            ? records.update(collection, record)
            : records.set(collection, record);
    }

    function setTab(e: MouseEvent) {
        const { id, innerText } = e.currentTarget as HTMLButtonElement;
        activeTab = innerText;
    }
</script>

<Aside {open} {close} right on:submit={submitRecord} on:reset={resetRecord}>
    <h3 slot="header">{header} {active?.id || ""}</h3>
    {#if active?.id && active?.updated}
        <p class="cols col-fit" style="--cols-gap: var(--gap-sm)">
            <small><span>Created:</span> {date(Number(active?.id))}</small>
            <small><span>Updated:</span> {date(Number(active?.updated))}</small>
        </p>
    {/if}
    <!-- <Await promise={schemas.get(collection).then(getRecord)}> -->
    <!-- {#if $schemas.length} -->
    <fieldset>
        <legend role="group">
            {#each tabs as tab}
                <button
                    id={tab}
                    type="button"
                    disabled={activeTab === tab}
                    on:click={setTab}>{tab}</button
                >
            {/each}
        </legend>

        {#if activeTab === "Form"}
            <label>
                <small><Icon icon="hash" /> ID</small>
                <input
                    name="id"
                    type="text"
                    value={recordID}
                    placeholder="Autogenerated"
                />
            </label>
            {#each makeRecord() as { type, ...props }}
                {#if type === "checkbox"}
                    <Checkbox {...props} />
                {:else if type === "textarea"}
                    <Textarea {...props} />
                {:else if type === "select"}
                    <Select {...props} />
                {:else if type === "json"}
                    <Json {...props} />
                {:else if type === "markdown"}
                    <Markdown {...props} />
                {:else if type === "file"}
                    <InputFile {...props} />
                {:else}
                    <Input {type} {...props} />
                {/if}
            {/each}
        {:else if activeTab === "Code"}
            <Code input={JSON.stringify(makeRecord(), null, 2)} />
        {/if}
    </fieldset>
    <!-- </Await> -->
    <!-- {/if} -->
</Aside>
