<script lang="ts" context="module">
    import { fragment, query } from "svelte-pathfinder";
    import { schemas, records, type Item } from "$client/stores/data.js";
    import Await from "$client/components/Await.svelte";
    import Aside from "$client/components/Aside.svelte";
    import Icon from "$client/components/Icon.svelte";
    import Code from "$client/components/Code.svelte";
    import Input from "./record/input.svelte";
    import Checkbox from "./record/checkbox.svelte";
    import Textarea from "./record/textarea.svelte";
    import Select from "./record/select.svelte";
    import InputFile from "./record/file.svelte";
    import Json from "./record/json.svelte";
    import Markdown from "./record/markdown.svelte";

    import { date } from "$client/utils/time.js";
    import { files } from "$client/stores/files.js";
    import { Schema } from "$client/stores/schemas.js";
</script>

<script lang="ts">
    export let file: string = "";
    export let active: Item | null = null;
    export let open = false;
    export let close = () => fragment.set("");
    export let header = "Add record";

    function getRecord() {
        active = $records?.find((r) => r.id === $query.record) || {};
    }
    function makeRecords() {
        const fn = (s: any) =>
            active?.[s.name] ? { ...s, value: active[s.name] } : s;
        return active ? $schemas.map(fn) : $schemas;
    }
    function submitRecord(e: SubmitEvent) {
        const data = new FormData(e.currentTarget as HTMLFormElement);
        const entries = Object.fromEntries(data);
        console.log(data, entries);

        let record: Record<string, any> = {};

        for (const name in entries) {
            const { type } = $schemas.find((s) => s.name === name) || {};

            switch (type) {
                case "checkbox":
                    record[name] = Boolean(entries[name]);
                    break;
                case "number":
                    record[name] = Number(entries[name]);
                    break;
                case "file":
                    const fileList = data.getAll(name) as Array<File>;
                    const values = data.getAll("value");

                    console.log(fileList, values, active);

                    const uploadFiles = fileList.map((f) => {
                        if (f.name) files.add(file, f);
                    });
                    Promise.all(uploadFiles);
                    type Link = Record<string, string | number>;
                    const links = fileList.reduce<Link[]>((a, File) => {
                        if (File.name) {
                            const { name, type, size } = File;
                            a.push({
                                name: encodeURI(name),
                                type,
                                size,
                                collection: file,
                                record: record.id,
                            });
                        }
                        return a;
                    }, []);
                    record[name] = active?.id
                        ? links.concat(active[name])
                        : links;
                    break;

                default:
                    if (name === "id") {
                        record[name] = Number(entries[name]) || Date.now();
                    } else record[name] = entries[name];
                    break;
            }
        }

        $fragment.includes(`#edit-record`)
            ? records.update(file, record)
            : records.set(file, record);
    }
</script>

<Aside {open} {close} right on:submit={submitRecord}>
    <h3 slot="header">{header} {active?.id || ""}</h3>
    {#if active?.id && active?.updated}
        <p class="cols col-fit" style="--cols-gap: var(--gap-sm)">
            <small><span>Created:</span> {date(Number(active?.id))}</small>
            <small><span>Updated:</span> {date(Number(active?.updated))}</small>
        </p>
    {/if}
    <Await promise={schemas.get(file).then(getRecord)}>
        <fieldset>
            <legend class="buttons-group">
                <a href={$fragment} role="button" aria-disabled="true">Form</a>
                <a href={$fragment} role="button">Code</a>
            </legend>
            <label>
                <small><Icon icon="number" /> ID</small>
                <input
                    name="id"
                    value={active?.id || ""}
                    placeholder="Autogenerated"
                />
            </label>
            {#each makeRecords() as { type, ...props }}
                {#if type === "checkbox"}
                    <Checkbox {...props} />
                {:else if type === "textarea"}
                    <Textarea {...props} />
                {:else if type === "select"}
                    <Select {...props} />
                {:else if type === "json"}
                    <Json {...props} />
                {:else if type === "markdown"}
                    <Markdown {...props} />
                {:else if type === "file"}
                    <InputFile {...props} />
                {:else}
                    <Input {type} {...props} />
                {/if}
            {/each}
        </fieldset>
    </Await>
</Aside>
